apiVersion: v1
kind: Pod
metadata:
  name: day1-prod-pos
  namespace: prod
  labels:
    cloudhrdk.com/env: prod
spec:
  containers:
  - name: day1-prod-pos
    image: alpine/curl:8.9.0
    command: ["sleep", "86400"]
