apiVersion: v1
kind: Pod
metadata:
  name: day1-prod-neg
  namespace: prod
  labels:
    cloudhrdk.com/env: dev
spec:
  containers:
  - name: day1-prod-neg
    image: alpine/curl:8.9.0
    command: ["sleep", "86400"]
