on:
  push:
  workflow_dispatch:

jobs:
  deploy_site:
    runs-on: ubuntu-latest
    container: 
      image: src.pmh.codes/build-tools/react2minio:latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: './pack'
      - run: mc alias set minio http://minio-service.minio.svc.cluster.local:9000 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}                    
      - run: tar czvf pack.tar.gz ./pack/. --exclude .git
      - run: mc cp $PWD/pack.tar.gz minio/pub/releases/cocktail.tar.gz
