on:
  push:
  workflow_dispatch:

jobs:
  deploy_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: './pack'
      - run: |
          wget https://dl.min.io/client/mc/release/linux-arm64/mc -O /tmp/mc
          chmod +x /tmp/mc
          /tmp/mc alias set minio http://minio-service.minio.svc.cluster.local:9000 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}                    
      - run: tar cvf pack.tar ./pack/*
      - run: /tmp/mc cp $PWD/pack.tar minio/cocktail/pack.tar --overwrite
