on:
  push:
  workflow_dispatch:

jobs:
  deploy_site:
    runs-on: ubuntu-latest
    container: 
      image: src.pmh.codes/build-tools/react2minio:latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: './pack'
      - run: mc alias set minio http://minio-service.minio.svc.cluster.local:9000 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}                    
      - run: tar cvf pack.tar ./pack/*
      - run: /tmp/mc cp $PWD/pack.tar minio/cocktail/pack.tar
