apiVersion: apps/v1
kind: Deployment
metadata:
  name:  token
  namespace: skills
  labels:
    app:  token
spec:
  selector:
    matchLabels:
      app: token
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  token
    spec:
      containers:
      - name:  token
        image:  648911607072.dkr.ecr.ap-northeast-2.amazonaws.com/token:3
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "45"]
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: REDIS_HOST
          value: clustercfg.skills-redis-cluster.afaync.apn2.cache.amazonaws.com
        - name: REDIS_PORT
          value: '6378'
        ports:
        - containerPort: 8080
          name:  token
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: token
  namespace: skills
spec:
  selector:
    app: token
  type: ClusterIP
  ports:
  - name: token
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: token
  namespace: skills
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: token
  minReplicas: 2
  maxReplicas: 64
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 10
