apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretmanager
  namespace: wsc-prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret 
  namespace: wsc-prod
spec:
  refreshInterval: 1s
  secretStoreRef:
    kind: SecretStore
    name: secretmanager
    target:
      name: db-secret
  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: wsc-app
        property: username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: wsc-app
        property: password
    - secretKey: MYSQL_HOST
      remoteRef:
        key: wsc-app
        property: host
    - secretKey: MYSQL_PORT
      remoteRef:
        key: wsc-app
        property: port
    - secretKey: MYSQL_DBNAME
      remoteRef:
        key: wsc-app
        property: dbname
