apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretmanager
  namespace: <NAMESPACE>
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2 # <-- Secret Region
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret 
  namespace: <NAMESPACE>
spec:
  refreshInterval: 1s
  secretStoreRef:
    kind: SecretStore
    name: secretmanager
    target:
      name: db-secret  # <-- K8s Secret Name
  data:
    - secretKey: MYSQL_USER  # <-- K8s Secret Key
      remoteRef:
        key: wsc-app # <-- SecretManager Secret Name
        property: username # <-- SecretManager Secret Key
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: wsc-app
        property: password
    - secretKey: MYSQL_HOST
      remoteRef:
        key: wsc-app
        property: host
    - secretKey: MYSQL_PORT
      remoteRef:
        key: wsc-app
        property: port
    - secretKey: MYSQL_DBNAME
      remoteRef:
        key: wsc-app
        property: dbname
