apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        dedicated: app
    spec:
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: 
            - "on-demand"
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - c6g.large
      taints:
      - key: dedicated
        value: app
        effect: "NoExecute"
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1
        kind: EC2NodeClass
        name: default
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  detailedMonitoring: true
  tags:
    Name: project-mng-app
    owner: pmh_only
  amiFamily: Bottlerocket # AL2, AL2023 or Bottlerocket
  role: karpenter-us-wsi-eks-cluster-20241213075611351300000031
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "us-wsi-eks-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "us-wsi-eks-cluster"
