apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretmanager
  namespace: wsc2024
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1 # <-- Secret Region
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret 
  namespace: wsc2024
spec:
  refreshInterval: 1s
  secretStoreRef:
    kind: SecretStore
    name: secretmanager
  target:
    name: dbinfo  # <-- K8s Secret Name
  data:
    - secretKey: MYSQL_USER  # <-- K8s Secret Key
      remoteRef:
        key: wsc2024-secret # <-- SecretManager Secret Name
        property: username # <-- SecretManager Secret Key
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: wsc2024-secret
        property: password
    - secretKey: MYSQL_HOST
      remoteRef:
        key: wsc2024-secret
        property: host
    - secretKey: MYSQL_PORT
      remoteRef:
        key: wsc2024-secret
        property: port
    - secretKey: MYSQL_DBNAME
      remoteRef:
        key: wsc2024-secret
        property: dbname
