apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamodb
  namespace: wsc2024
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::648911607072:role/wsc2024-prod-role-dynamodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  order-deploy
  namespace: wsc2024
  labels:
    app:  order
spec:
  selector:
    matchLabels:
      app: order
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  order
    spec:
      serviceAccountName: dynamodb
      nodeSelector:
        dedicated: app
      tolerations:
        - key: dedicated
          value: app
          effect: NoSchedule
      containers:
      - name:  order
        image:  648911607072.dkr.ecr.us-east-1.amazonaws.com/order-repo:latest
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "45"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: AWS_REGION
          value: us-east-1
        ports:
        - containerPort: 8080
          name:  order
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: wsc2024
spec:
  selector:
    app: order
  type: ClusterIP
  ports:
  - name: order
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order
  namespace: wsc2024
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-deploy
  minReplicas: 2
  maxReplicas: 64
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 30
