apiVersion: apps/v1
kind: Deployment
metadata:
  name:  event
  namespace: default
  labels:
    app:  event
spec:
  selector:
    matchLabels:
      app: event
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  event
    spec:
      serviceAccountName: sm
      nodeSelector:
        dedicated: app
      tolerations:
        - key: dedicated
          value: app
          effect: NoSchedule
      readinessGates:
        - conditionType: target-health.alb.ingress.k8s.aws/ap-wsi-endpoint_event_8080
      containers:
      - name:  event
        image: 648911607072.dkr.ecr.ap-northeast-2.amazonaws.com/event:2024-12-12.13.45.36
        command:
          - /app/event
        args:
          - "-SecretsManagerName=wsi-event"
          - "-Region=ap-northeast-2"
          - "-TokenEndpoint=http://token:8080"
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "45"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          name:  event
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: event
  namespace: default
spec:
  selector:
    app: event
  type: ClusterIP
  ports:
  - name: event
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: event
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: event
  minReplicas: 2
  maxReplicas: 64
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
---
