apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretsmanager
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::648911607072:role/ap-unicorn-role-secretsmanager2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  unicorn
  namespace: dev
  labels:
    app:  unicorn
spec:
  selector:
    matchLabels:
      app: unicorn
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  unicorn
    spec:
      serviceAccountName: secretsmanager
      nodeSelector:
        app: apps
      tolerations:
        - key: dedicated
          value: app
          effect: NoSchedule
      readinessGates:
        - conditionType: target-health.alb.ingress.k8s.aws/unicorn-ingress_unicorn_8080
      containers:
      - name:  unicorn
        image: 648911607072.dkr.ecr.ap-northeast-2.amazonaws.com/unicorn:v1
        args: ["-region", "ap-northeast-2", "-secretName", "unicorn-secret", "-tokenEndpoint", "http://token.dev.svc.cluster.local:8080"]
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "45"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          name:  unicorn
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: unicorn
  namespace: dev
spec:
  selector:
    app: unicorn
  type: ClusterIP
  ports:
  - name: unicorn
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: unicorn
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unicorn
  minReplicas: 2
  maxReplicas: 64
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 30
